GoogleChromeLabs/web-audio-samples

samples/audio/convolution-effects.html
It is an error to set the buffer attribute of an AudioBufferSourceNode
more than once.  So, in this demo we need to create a new
AudioBufferSourceNode every time a new sound is to be played.
Fixes issue #52.
=> Create a new AudioBufferSource node for each source.

samples/audio/box2d-js/box2d-audio.html, samples/audio/convolution-effects.html, samples/audio/dj.html, samples/audio/doppler.html, samples/audio/javascript-processing.html, samples/audio/o3d-webgl-samples/pool.html, samples/audio/shiny-drum-machine.html, samples/audio/simple.html, samples/audio/subtractive.html, samples/audio/wavetable-synth.html
Chrome canaries will print deprecation warnings about using
webkitAudioContext.  Update examples not to use webkitAudioContext.
I didn't fix all of demos; just the ones linked from index.html are
fixed.
=> Fix issue #51: Use AudioContext instead of webkitAudioContext when possible

samples/audio/box2d-js/box2d-audio.html, samples/audio/wavetable-synth.html
Added explicit cleanup of finished audio nodes. This avoids gradual performance degradation due to lazy garbage collection. By explicitly disconnecting ABSN and other voice-related nodes from the audio graph once they're finished, we can avoid the situation where CPU load keeps increasing although number of playing nodes do not.
If you click garbage collect in the dev tools some of the CPU load goes away so this is probably related to Chrome web audio internal garbage collection.
=> Explicit cleanup of finished audio nodes

poly-synth/index.html, poly-synth/src/poly-synth-demo.js, poly-synth/src/poly-synth-voice.js, poly-synth/src/poly-synth.js
This PR resolves [issue #100 ](https://github.com/GoogleChrome/web-audio-samples/issues/100). 
- poly-synth/index.html now has containers for filter and volume ADSR.
- poly-synth/src/poly-synth-demo.js now adds GUI elements for controlling filter and volume ADSR.
- poly-synth/src/poly-synth.js now has default values for filter and volume ADSR.
- poly-synth/src/poly-synth-voice.js now implements logic for filter ADSR.
The demo can be found [here](http://rawgit.com/GoogleChrome/web-audio-samples/55e6838d614479cfe39ea8b734005d4888079fb4/poly-synth/index.html). 
The parameters currently do not support nonlinear scaling. This is a desirable feature and entails modifying audio-worklet/lib/param-controllerer.js. This should be done in a separate PR, and is listed in issue #106
=> Implemented filter ADSR logic and volume and filter ADSR GUI controls.

audio-worklet/noisegate.html, audio-worklet/src/noisegate-demo.js
In this PR, audio-worklet/noisegate.html and audio-worklet/src/noisegate-demo.js have been modified to support audio-worklet/src/noisegate-audio-worklet.js. The audio worklet version only works if the browser supports audio worklets. 
The demo can be found [here](http://rawgit.com/GoogleChrome/web-audio-samples/2d62ef30ef41c7850c394428767c0e53a68ee695/audio-worklet/noisegate.html).
=> Noise gate demo integrated with the worklet

poly-synth/index.html, poly-synth/src/poly-synth-demo.js, poly-synth/src/poly-synth-voice.js, poly-synth/src/poly-synth.js
In this PR, three master effects have been added to the poly-synth: convolution, feedback delay, and bitcrushing. The PR modifies 4 files:
- poly-synth/index.html: added one dependency, and changed the GUI
- poly-synth/src/poly-synth-demo.js: added GUI components for master effects and impulse response loading.
- poly-synth/src/poly-synth.js: added the audio graph supporting effects and controls for changing effects settings.
- poly-synth/src/poly-synth-voice.js: removed an extraneous blank line!
The demo can be found [here](http://rawgit.com/GoogleChrome/web-audio-samples/8a4615e3124b83c4f783f4c188a8d302ab1f943b/poly-synth/index.html). As I evaluate the demo online, I notice that it takes a couple seconds to load. This is because it takes time to load the impulse response buffers. I may …
=> Added three master effects to the poly-synth

audio-worklet/noisegate-test.html
Added three tests verify that the noise gate's threshold matches the input power closely. This is response to issue #94.
=> Noise gate threshold tests

poly-synth/src/poly-synth-demo.js, poly-synth/src/poly-synth.js
This quick [patch](https://github.com/GoogleChrome/web-audio-samples/commit/d260d6e7a7b9a2998c6cab759538c854bcab53bd) fixes the poly synth drum not stopping bug. 
The demo is [here](http://rawgit.com/GoogleChrome/web-audio-samples/d260d6e7a7b9a2998c6cab759538c854bcab53bd/poly-synth/index.html)
=> Fixed poly-synth-bug-drum-bug

audio-worklet/lib/audio-worklet-helper.js
=> Add a check for `AudioWorkletNode` when sniffing AudioWorklet features

audio-worklet/index.html
The link is now exposed to social media, so it is helpful get some early feedback through the demo page.
=> Add a link for templated bug report

audio-worklet/index.html, audio-worklet/lib/audio-worklet-helper.js, resources/base-v2.css
- This change is a requirement for Origin Trials process. ([link](https://www.chromium.org/blink/origin-trials/running-an-origin-trial#add-to-signup-form
))
- Currently the link to Google developer article is missing. This landing page is the prerequisite for the article to be published.
- The style change for the demo pages will be updated once this PR is merged.
[Preview](https://cdn.rawgit.com/GoogleChromeLabs/web-audio-samples/dcb3bb71f1bd8a2fbe3882f176a170c8e64d55c9/audio-worklet/index.html)
=> New AudioWorklet project landing page

stress-test/boxes/js/lib.js
Currently, the stress-test demo only works in Chrome, not in Firefox. Firefox throws a ```ReferenceError: event is not defined``` because the function argument is called ```clickEvent```, not ```event```. I'm not sure why the code works in Chrome, but with this change, it will work in both browsers.
=> Fix stress-test bug

samples/audio/shiny-drum-machine.html
Gets rid of the mixed content error messages.
=> Fix #157: Load fonts using https

audio-worklet/design-pattern/shared-buffer/shared-buffer-worker.js, audio-worklet/design-pattern/shared-buffer/shared-buffer-worklet-processor.js
`wake()` is deprecated https://www.chromestatus.com/feature/6228189936353280
=> Substitute Atomics.notify() for Atomics.wake()

assets/Components.js, audio-worklet/design-pattern/shared-buffer/index.html, src/components/Components.js
Fixes #195
1. Gate duplicate creations of OfflineAudioContext in the detection code.
2. Handle browsers with old prefix.
3. Use dynamic import for the AudioWorkletNode extension for browsers with no Audio Worklet support
=> Improve Audio Worklet pages for browsers with no support

audio-worklet/design-pattern/lib/wasm-audio-helper.js
Previously had an address right-shifting by the number of bytes in a uint16, which was non-sensical but working because right shifting by 2 is equivalent to dividing by the number of bytes in f32 (the actual intention). This change makes the code more faithful to intent.
=> Fix confusing pointer math in HeapAudioBuffer

audio-recorder/app.mjs, audio-recorder/index.html, audio-recorder/indexeddb-storage.mjs, audio-recorder/style.css
See #205 
Recorder now automatically persists recorded audio clips using the browser's IndexedDB ObjectStorage. When reloading the page, recorded clips do not get lost any longer.
As a trade-off, the waveform is only shown during recording and hidden after the recording is finished. Otherwise, it would need to be persisted or recomputed when clips are being loaded from storage. Persisting the waveform would block a future implementation of a file system based storage, which could allow loading arbitrary audio files. Recomputing the waveform works very differently: AnalyserNode can not be used, because there is no audio stream. We'd need to compute it manually based on decoded audio samples, which is expensive in JavaScript and out of scope for me.
=> Persist audio recordings to IndexedDB.

archive/demos/shiny-drum-machine-data.js, archive/demos/shiny-drum-machine-ui.js, archive/demos/shiny-drum-machine.html, archive/demos/shiny-drum-machine.js, archive/demos/style/drummachine.css
See #226.
Sorry for the huge PR. Now that the code is a bit cleaned up and modularized, I hope that follow up PRs can be shorter.
* Use data attributes to remove hardcoded IDs and URLs from note buttons.
* Introduce Slider ViewModel to simplify two-way binding.
* Compute playbackRate on the fly to reduce data duplication.
* Introduce button data-attrs to replace hardcoded URLs and IDs.
* Refactor Kit to use ES6-class, fetch, and Promises.
* Refactor to ES6 module, extract static data to data.js.
* Refactor and extract UI bindings to ui.js.
* Refactor hardcoded instrument mappings.
=> Refactor Drum Machine UI and sample loading code.

.eslintrc.json, archive/demos/shiny-drum-machine-audio.js, archive/demos/shiny-drum-machine-ui.js, archive/demos/shiny-drum-machine.html, archive/demos/shiny-drum-machine.js, archive/demos/style/drummachine.css, package.json
- Introduced Beat class to manage stateful beat data structure.
- Introduce Player class to schedule playback and handle audio routing.
- Refactor beat position LED display to decouple HTML and JS.
- Simplify audio scheduling logic.
- Ignore all pre-existing files that violate eslint in eslint config, so that `npm run lint .` can be executed in the repository without failing due to old files.
This concludes most refactorings for drum machine, let's discuss next steps on Thursday.
See #226
=> Refactor drum machine audio playback and scheduling

audio-worklet/PageData.js, audio-worklet/basic/audio-worklet-node-options/PageData.js, audio-worklet/basic/audio-worklet-node-options/basic-processor.js, audio-worklet/basic/audio-worklet-node-options/index.html
I wrote this example for issue regarding #131 .
In this example we can pass type and frequency options to AudioWorkletNode constructor and use those in AudioWorkletProcessor.
Here is how it looks like.
https://divyamahuja.github.io/web-audio-samples/audio-worklet/basic/audio-worklet-node-options/ 
I wonder if this will work for #131 issue
=> Add example for AudioWorkletNode constructor options parameter

.eslintrc.json, src/_data/audioworklet_data.yaml, src/_data/build_info.json, src/audio-worklet/free-queue/examples/simple-passthrough/basic-processor.js, src/audio-worklet/free-queue/examples/simple-passthrough/coi-serviceworker.js, src/audio-worklet/free-queue/examples/simple-passthrough/constants.js, src/audio-worklet/free-queue/examples/simple-passthrough/index.njk, src/audio-worklet/free-queue/examples/simple-passthrough/main.js, src/audio-worklet/free-queue/examples/simple-passthrough/worker.js
This PR adds an basic example of FreeQueue.
In this example, audio data is sent to worker through inputQueue (FreeQueue Instance), and then is processed by worker(each sample is multiplied by 0.5), and is pushed to outputQueue(FreeQueue Instance).
AudioWorklet then pulls data out of outputQueue and renders it.
I also added [coi-serviceworker.js](https://github.com/gzuidhof/coi-serviceworker) to make it workable with GitHub pages.
Working Example - [Example](https://divyam.dev/web-audio-samples/audio-worklet/free-queue/examples/simple-passthrough/)
=> Add basic FreeQueue example

src/_data/build_info.json, src/audio-worklet/migration/worklet-recorder/app.js, src/audio-worklet/migration/worklet-recorder/index.njk, src/audio-worklet/migration/worklet-recorder/recording-processor.js
#294 issue solution.
The  AudioWorklet Recorder demo is not able to preview and download the recording when the record time reach the maximum limit. I also extend the max recording time to 5 mins and provide better user experience of using this demo.
=> Fixing the bug in AudioWorklet Recorder demo

package-lock.json, package.json, src/_data/build_info.json
Fixes #305.
Upgraded the following packages:
- @11ty/eleventy: 2.0.1
- @11ty/eleventy-navigation: 0.3.5
- autoprefixer: 10.4.14
- cssnano: 6.0.1
- eslint: 8.40.0
- postcss: 8.4.23
- postcss-cli: 10.1.0
- prettier: 2.8.8
- rimraf: 5.0.1
- tailwindcss: 3.3.2
=> Upgrading NPM modules

src/_data/build_info.json, src/_data/tests_data.yaml, src/tests/pannernode/app.js, src/tests/pannernode/index.njk
This PR adds a manual test for PannerNode, which can be useful when the team verify the PannerNode improvement on issues (e.g. GC, processing artifacts) in the future.
=> Adding a manual test for PannerNode

src/_data/build_info.json, src/audio-worklet/design-pattern/wasm-supersaw/Makefile, src/audio-worklet/design-pattern/wasm-supersaw/README.md, src/audio-worklet/design-pattern/wasm-supersaw/synth.wasm.js
Fixes #348.
The latest stable of Emscripten 3.1.47 caused some runtime errors in the WASM SuperSaw example, and this PR fixes the problem. The details can be found here: https://github.com/GoogleChromeLabs/web-audio-samples/issues/348#issuecomment-1791272814
=> Fix Emscripten runtime failure

src/audio-worklet/design-pattern/lib/wasm-audio-helper.js
In https://github.com/GoogleChromeLabs/web-audio-samples/issues/347 ,
I updated the index directly instead of making a new temporary every iteration, which removes the inefficiency.
=> Fix: #347 : Improve RingBuffer

src/_data/landing_data.yaml
Noticed that Wavetable Synthesizer, AnalyserNode with visualization, Panning and Reverberation, and WebGL Pool with 3d audio didn't have descriptions so added them. Perhaps might be more than a non-functional change.
=> Add 4 descriptions to landing page demos

package.json
Downgrade eslint from 9.5.0 to 8.57.0 to be compatible with eslintrc.
=> Downgrade eslint to be compatible with eslintrc

src/audio-worklet/migration/worklet-recorder/recording-processor.js
This is to fix #376.
This value is no longer used anywhere.  The gain message parameter is never read.
=> Remove unused sampleSum from recording_processor.js

src/_data/build_info.json, src/audio-worklet/basic/hello-audio-worklet/main.js
I added a stop button to the hello audio worklet example enabling the user to stop and start the sound. 
Specifically, I used audioContext.suspend() to allow the user to pause the sound with a stop button. And I added an isModuleLoaded check to avoid redundantly calling addModule. Also added isPlaying to toggle the playing state.
=> Added stop button for hello audio worklet example

src/tests/playwright/README.md, src/tests/playwright/pages/chuck-realtime-sine.html, src/tests/playwright/pages/index.html, src/tests/playwright/pages/live-suite/scripts/main.js, src/tests/playwright/pages/live-suite/scripts/test-file-converter.js, src/tests/playwright/pages/live-suite/style.css, src/tests/playwright/pages/perf-audio-buffer-source-node.html, src/tests/playwright/pages/perf-audio-worklet-node.html, src/tests/playwright/pages/perf-biquad-filter-node.html, src/tests/playwright/pages/perf-dynamics-compressor-node-knee.html, src/tests/playwright/pages/perf-dynamics-compressor-node-post-knee.html, src/tests/playwright/pages/perf-dynamics-compressor-node-pre-knee.html, src/tests/playwright/pages/perf-gain-node.html, src/tests/playwright/pages/perf-gain.html, src/tests/playwright/pages/perf-panner-node.html, src/tests/playwright/pages/perf-panner.html, src/tests/playwright/pages/perf-timeline-insert-event.html, src/tests/playwright/pages/realtime-sine.html, src/tests/playwright/pages/tests.json, src/tests/playwright/pages/util/audit.js, src/tests/playwright/pages/util/bypass-processor.js, src/tests/playwright/pages/util/recorder/recorder-main.js, src/tests/playwright/pages/util/recorder/recorder-processor.js, src/tests/playwright/runner.spec.ts
Porting Performance Tests from https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/perf_tests/webaudio/
to Web Audio Test Suite
=> Playwright Port Performance Tests

.eleventy.js, src/lib/free-queue/coi-serviceworker.js, src/lib/free-queue/free-queue.js, src/lib/free-queue/test/free-queue.test.html, src/lib/free-queue/test/free-queue.test.js
- Test cases for FreeQueue Class 
Fixes https://github.com/GoogleChromeLabs/web-audio-samples/issues/347
=> FreeQueue: automated test coverage

docs/kizjkre-gsoc24.md
Thanks for a great GSoC @hoch and @mjwilson-google!
=> Add contribution documentation for Google Summer of Code 2024

src/rainfly/README.md
Documented @sampleRate parameter syntax in README. Let me know if any changes are needed.
=> Add parameter syntax documentation in README

src/demos/wavetable-synth/index.html
The wavetable synth will not make sound if it is navigated to directly, because there isn't a user gesture so the autoplay rules will be enforced.
This PR adds listeners to allow the user to click or press a key to start playing, even if the page is loaded directly.
=> Add listener to wavetable synth for autoplay

src/audio-worklet/free-queue/src/free-queue.js, src/experiments/webgpuaudio/lib/free-queue.js, src/lib/free-queue/benchmark/memory-allocation-demo.html, src/lib/free-queue/free-queue-sab.js
The original FreeQueueSAB implementation used `Float32Array.subarray()` extensively in the `push()` and `pull()` methods. According to the ECMAScript specification, `subarray()` creates new TypedArray views, which can cause:
1. **Memory Allocation**: Each `subarray()` call potentially creates a new view object
2. **GC Pressure**: Frequent allocations in real-time audio processing can trigger garbage collection pauses
3. **Browser Inconsistency**: Optimization behavior varies across browsers and isn't guaranteed
```javascript
// Before optimization - creates temporary views
const blockA = this.channelData[channel].subarray(currentWrite);
const blockB = this.channelData[channel].subarray(0, nextWrite);
blockA.set(input[channel].subarray(0, blockA.length)); …
```
=> fix: Float32Array.subarray() Memory Allocation
