- samples/audio/MediaElementAudioSourceNode.html
- samples/audio/convolution-effects2.html
- samples/audio/drum-machine.html
- samples/audio/javascript-processing2.html
- samples/audio/latency-test.html
- samples/audio/latency.html
- samples/audio/loop-points.html
- samples/audio/loop.html
- samples/audio/offline-convolution.html
- samples/audio/offline-rendering.html
- samples/audio/pingpong-delay.html
- samples/audio/playthrough.html
- samples/audio/samplerate.html
- samples/audio/simple-mixing.html
- samples/audio/synthetic-clock.html
- samples/audio/test-waveshaper.html
- samples/audio/tone-editor.html
- samples/audio/tone.html
- samples/audio/visualizer-chorus.html
- samples/audio/visualizer-live-doubling.html
- samples/audio/visualizer-live.html
- samples/audio/visualizer-noise.html
- samples/audio/visualizer2-gl.html
- samples/audio/waveshaper-oversample.html
- samples/audio/wavetable-synth2.html
- samples/audio/zero-crossings.html
webkitAudioContext is deprecated.
> Fixed to use AudioContext

- samples/audio/convolution-effects2.html
- samples/audio/drum-machine.html
- samples/audio/javascript-processing2.html
- samples/audio/latency-test.html
- samples/audio/latency.html
- samples/audio/loop.html
- samples/audio/offline-convolution.html
- samples/audio/offline-rendering.html
- samples/audio/panning.html
- samples/audio/pingpong-delay.html
- samples/audio/simple-mixing.html
- samples/audio/tone.html
- samples/audio/visualizer-chorus.html
- samples/audio/visualizer-noise.html
- samples/audio/visualizer2-gl.html
- samples/audio/waveshaper-oversample.html
createBuffer that is designated ArrayBuffer is abolished.
> Fixed to use decodeAudioData

- samples/audio/flot-axislabels/README.md
- samples/audio/flot-axislabels/jquery.flot.axislabels.js
- samples/audio/timeline.html
Primarily adds an example of setTargetAtTime.
Secondarily, replace the old graph code with flot which produces a nicer looking graph.  Can't save the graph as an image anymore, but a screenshot works just as well.
> Update timeline demo

- samples/audio/doppler.html
in PannerNode and AudioListener.
> Correspond to deprecated API

- index.html
- resources/base.css
I put the quick link section to our favorite demos. We have multiple 'index' pages here and there, but this index should be the entry point for everything. I intend to continue to work on this.
> Organize the index page.

- .gitignore
- stress-test/boxes/js/app.js
- stress-test/boxes/js/web-audio.js
PTAL.
With this change, you actually see the node counter increase correctly as you create objects.
> Box2D stress test: object counter correctly reflects total node count

- audio-worklet/test/audit-util.js
- audio-worklet/test/audit.js
- audio-worklet/test/testharness.js
- audio-worklet/test/testharness.js is an exact copy of [testharness.js](https://cs.chromium.org/chromium/src/third_party/WebKit/LayoutTests/resources/testharness.js?q=testharness.js&dr=C&l=2600) at 2017-08-02
- audio-worklet/test/audit.js is an exact copy of [audit.js](https://cs.chromium.org/chromium/src/third_party/WebKit/LayoutTests/webaudio/resources/audit.js?q=audit.js&dr=C&l=39) at 2017-08-02
- audio-worklet/test/audit-util.js is an exact copy of [audit-util.js](https://cs.chromium.org/chromium/src/third_party/WebKit/LayoutTests/webaudio/resources/audit-util.js?dr=C) at 2017-08-02
> Added testing utilities for noisegate

- poly-synth/src/poly-synth-demo.js
- poly-synth/src/poly-synth-voice.js
- poly-synth/src/poly-synth.js
This PR is in reference to issues #109 and #110. Both these issues have been resolved and the new demo can be found at
http://rawgit.com/GoogleChrome/web-audio-samples/40f68d0e23c882065242eebd73506130ede65fc5/poly-synth/index.html
> Fixed Q and sustain bugs in the poly-synth.

- audio-worklet/src/noisegate-audio-worklet.js
This PR has a single file implementing a worklet counterpart to audio-worklet/src/noisegate-script-processor.js. It resolves issue #102.
> Added a worklet implementation of the noisegate.

- audio-worklet/lib/audio-worklet-helper.js
> Remove redundant/incorrect check from audio-worklet-helper.js

- audio-worklet/basic/bit-crusher.html
- audio-worklet/basic/event-processor-state.html
- audio-worklet/basic/hello-audio-worklet.html
- audio-worklet/basic/message-port.html
- audio-worklet/basic/noise-audio-param.html
- audio-worklet/basic/one-pole.html
- audio-worklet/index.html
This is to prepare Origin Trial activation with M64 Beta. Also includes:
- Minor fixes on the text.
- Reordering demo links.
> Adds Origin Trial Token

- audio-worklet/index.html
> Update the text for M64 stable availability.

- samples/audio/mag-phase.html
When user selects a source, resume the context so that audio will
play.  Also added a "None" source as the default so the user has to
click on some source button to hear anything.
> Resume context on user gesture

- audio-worklet/basic/bit-crusher.html
- audio-worklet/basic/event-processor-state.html
- audio-worklet/basic/hello-audio-worklet.html
- audio-worklet/basic/message-port.html
- audio-worklet/basic/noise-audio-param.html
- audio-worklet/basic/one-pole.html
> Update Origin Trial token

- audio-worklet/basic/bit-crusher.html
- audio-worklet/basic/hello-audio-worklet.html
- audio-worklet/basic/message-port.html
- audio-worklet/basic/node-onerror.html
- audio-worklet/basic/noise-audio-param.html
- audio-worklet/basic/one-pole.html
> Update OT Token (expires 4/10)

- audio-worklet/basic/hello-audio-worklet.html
- audio-worklet/basic/message-port.html
- audio-worklet/basic/node-onerror.html
- audio-worklet/basic/noise-audio-param.html
- audio-worklet/basic/one-pole.html
- audio-worklet/index.html
PTAL. This PR removes the obsolete text and the origin trial information for the M66 stable launch.
> Remove obsolete text and OT information

- audio-worklet/design-pattern/awn/Makefile
- audio-worklet/design-pattern/awn/index.html
Small typo.
-----------
Cool stuff -- thanks for providing these samples.
> Fix discrepancy between module name in index.html & Makefile

- assets/Components.js
- src/components/Components.js
> Fix DemoRunner's URL generator

- archive/stress-box/js/web-audio.js
> Fix incorrect URLs in Box2D stress test

- audio-worklet/PageData.js
- audio-worklet/basic/handling-errors/index.html
- audio-worklet/basic/message-port/PageData.js
- Remove redundant description from the demo.
- Change the link to the paper PDF to non-google drive.
- Clean up string concat to string literals.
> Small maintenance

- geiger/src/iframe/iframeHandler.js
- geiger/src/index.css
- geiger/src/index.js
- geiger/src/messaging/addEventListener.js
- geiger/src/messaging/startListening.js
- geiger/src/ui/Workspace.js
These files contain the entry point of the graph visualizer. 
The Workspace class acts as the Controller;
The Graph class acts as the Model;
The fabric.Canvas is the View.
More details of the Graph, layout, and render will be added later.
> Add the entry point and message listening

- audio-worklet/design-pattern/shared-buffer/shared-buffer-worker.js
> Fix pointer increment logic in shared-buffer-worker.js

- src/components/Components.js
fixes detection on unsupported browsers (tested with Safari v13.0.4)
fixes #195
> fix ReferenceError of undefined object

- audio-recorder/README.md
- audio-recorder/app.js
- audio-recorder/index.html
- audio-recorder/style.css
> Implement prototype audio recorder.

- audio-recorder/app.js
> Stop microphone access after recording is finished.

- audio-recorder/README.md
- audio-recorder/app.mjs
- audio-recorder/indexeddb-storage.mjs
> Apply eslint to audio-recorder

- drum-machine/index.html
Made a mistake on verification (rolling out is slow) so this fixes the path again.
> Fix the path again

- drum-machine/README.md
- drum-machine/index.html
This PR adds README file to the drum machine example. Also a small change to add a link to the source code.
> Added README and a link to the source code

- package.json
> Update version to 2.1.0

- .eslintrc.json
- audio-recorder/app.mjs
- audio-recorder/indexeddb-storage.mjs
- audio-recorder/service-worker.js
- audio-recorder/visualize.mjs
- package.json
This PR is a child of #224 - please review the parent PR first. 
See #205 .
> Support offline mode through ServiceWorker.

- .eslintrc.json
- audio-recorder/app.mjs
- audio-recorder/indexeddb-storage.mjs
- audio-recorder/visualize.mjs
- package.json
> Refactor and extract visualization to dedicated file.

- archive/demos/dj.html
- archive/demos/dj.js
- archive/demos/style/dj.css
Redesigned DJ sample to drag-n-drop based Material UI. Cleaned up repetitive code by introducing a `DeckPlayer` class for both decks.
See #232
> Redesign DJ sample to drag-n-drop based Material UI

- shiny-drum-machine/drummachine.css
- shiny-drum-machine/index.html
- shiny-drum-machine/shiny-drum-machine-audio.js
- shiny-drum-machine/shiny-drum-machine-ui.js
- shiny-drum-machine/shiny-drum-machine.js
- Clicking save downloads a JSON file to disk.
- Clicking load opens a file select dialog.
- Dragging a file into the browser window shows a dashed outline, dropping loads the file.
Fixes #226 .
> Modernize drum machine saving and loading

- audio-worklet/design-pattern/wasm-supersaw/index.html
I have added some basic html tags which were missing inside the index.html file of wasm-supersaw design pattern inside audio worklet directory.
Issue #241 is fixed by this pr.
> added header files to wasm-supersaw index

- assets/lit-html/README.md
...and a bit more in the description about lit's development status.
> Update link to lit documentation

- audio-worklet/PageData.js
- audio-worklet/basic/volume-meter/PageData.js
- audio-worklet/basic/volume-meter/index.html
- audio-worklet/basic/volume-meter/volume-meter.js
This PR adds a basic "Volume Meter" sample to show how to measure microphone volume with AudioWorkletProcessor.
@hoch Please review.
> Add volume meter sample

- src/experiments/webgpuaudio/gpu-processor.js
- src/experiments/webgpuaudio/worker.js
Makes both writing and reading audio work via WebGPU!
> Make GPU read also work

- src/experiments/webgpuaudio/gpu-processor.js
- src/experiments/webgpuaudio/worker.js
Use WebGPU shader language (WGSL) to write shaders that perform computations. The comments in the code should pinpoint the path taken to go from the writing all the way to the reading step.
The WORKGROUP_SIZE variable is used to parallelize the operation on WebGPU.
> Trying out WGSL for doing computations in GPU

- src/_data/build_info.json
- src/experiments/webgpuaudio/gpu-processor.js
- src/experiments/webgpuaudio/index.html
- src/experiments/webgpuaudio/ir-helper.js
- src/experiments/webgpuaudio/worker.js
- Added `ir-helper.js` for a simple IR buffer (Float32Array) creation. 
- Refactor `worker.js` for better readability and modularity.
> Adding ir-helper.js and refactor worker.js

- src/experiments/webgpuaudio/main.js
- src/experiments/webgpuaudio/worker.js
Now all the IR loading process can be done in the main thread. However, changing IR on the fly might need a redesign.
> Passing IR array from the main thread to the worker thread

- src/experiments/webgpuaudio/assets.js
- src/experiments/webgpuaudio/basic-processor.js
- src/experiments/webgpuaudio/constants.js
- src/experiments/webgpuaudio/index.njk
- src/experiments/webgpuaudio/lib/free-queue.js
- src/experiments/webgpuaudio/main.js
- src/experiments/webgpuaudio/worker.js
No functional changes except for tightening up parameters in constants.js.
> Clean up and refactoring

- .github/workflows/main.yml
- src/_data/build_info.json
- src/audio-worklet/migration/worklet-recorder/app.js
- src/audio-worklet/migration/worklet-recorder/index.njk
Fixing #298 The download button is not functional
> Fixing the AudioWorklet Recorder download button link

- src/_data/build_info.json
- src/audio-worklet/migration/spn-recorder/app.js
- src/audio-worklet/migration/spn-recorder/index.njk
- src/audio-worklet/migration/worklet-recorder/app.js
- src/audio-worklet/migration/worklet-recorder/index.njk
> Fixing the SPN broken demo and formating the worklet demo

- src/audio-worklet/migration/worklet-recorder/app.js
>  Fix functionality of "Turn monitor on/off" button in AudioWorklet Recorder

- src/CONTRIBUTING.md
Fixes #297.
No function changes.
> Add CONTRIBUTING.md

- src/_data/build_info.json
- src/audio-worklet/migration/spn-recorder/app.js
- src/audio-worklet/migration/worklet-recorder/app.js
Fix #316 
Splitting the gain value which is used in each visualization canvas.
Multiple the amplitude with a constant number 5 to improve the visualization.
> Splitting the visualization of canvas and improve readability of visulization

- src/_data/build_info.json
- src/audio-worklet/migration/spn-recorder/app.js
- src/audio-worklet/migration/spn-recorder/index.njk
- src/audio-worklet/migration/worklet-recorder/app.js
- src/audio-worklet/migration/worklet-recorder/index.njk
This is the PR to fix #325, #327, #328, #329. 
The code changed are mainly on the UI component. We add the button to make "start recording", "stop recording", "download files" as three individual button with their own functionality and improve the user readability and user experience in SPN and worklet recorder demo.
> Improve the UI design for SPN recorder and Worklet Audio recorder

- src/_data/build_info.json
- src/audio-worklet/migration/spn-recorder/app.js
- src/audio-worklet/migration/worklet-recorder/app.js
> Improve the sound wave of recording canvas

- src/audio-worklet/migration/spn-recorder/index.njk
- src/audio-worklet/migration/worklet-recorder/index.njk
#334 This PR updates the newest description of SPN and worklet recorder.
> Update SPN and worklet recorder description

- src/_data/build_info.json
- src/audio-worklet/migration/spn-recorder/app.js
- src/audio-worklet/migration/worklet-recorder/app.js
- src/library/FIFO.js
- src/library/VUMeter.js
- src/library/Waveform.js
#337 was closed accidentally, and this PR continues the work from #337. 
It includes:
- The new VU-Meter class
- Revising comments related to Worklet and SPN recording demo.
> VU-meter library design 2

- src/audio-worklet/design-pattern/lib/wasm-audio-helper.js
Fixed RingBuffer read / write indexes update.
Because of that error i faced lags during AudioWorklet process because of that.
Faced when RingBuffer length 48000 and kernelBufferSize - 512
> fixed ring buffer indexes updates in design patterns

- src/_data/build_info.json
- src/tests/resampler/app.js
- src/tests/resampler/index.njk
[WIP]
Adding a test page for the verification.
> Add  a test page for Issue 331682035

- src/tests/index.njk
**Added a `<p>` tag in `\tests\index.njk`** 
- Testing Purpose
- GSOC'24
> Non-functional code change for testing  

- package-lock.json
- src/_data/build_info.json
This fixes: #357, #345, #344, #343, #295
Locally tested and confirmed the build system after updating modules.
> Update outdated and probelmatic node modules

- package-lock.json
- package.json
- src/_data/build_info.json
- Version up to 3.2.0
- Upgraded several node modules to their latest version.
- Locally confirmed that there is no functional/visual change.
> Upgrade node modules packages to latest releases

- src/_data/build_info.json
- src/_data/landing_data.yaml
- src/_includes/base.njk
Added a comment to landing_data in anticipation of the Audio Worklets playground.
> Preparing resources documentation for Audio Worklets playground.

- .eleventy.js
- .github/workflows/main.yml
- src/_data/build_info.json
> Add style and realtime sine reference to live suite build

- src/tests/playwright/README.md
- src/tests/playwright/pages/realtime-sine.html
- src/tests/playwright/pages/template.html
Includes:
- How to write tests for Playwright and Live Suite running
- Sample `template.html` for test writing
- Notes for Playwright Configuration and Browser setup
- API documentation of `audit.js` and `recorder` object.
> Web Audio Test Suite Documentation

- src/lib/free-queue/test/free-queue-sab.test.js
Moved some test cases from the `FreeQueue Test Suite` and extended the test suite to cover more areas.
> Added more test cases - ChannelAdaption and ErrorHandling

- docs/abhay-gupta-GSOC-24.md
Here is the readme version of the final report!
Ready to merge. 
I'll make a commit in that PR to update the readme file after accomplishing the goal of package creation and documenting the result of the comparison.
> Added the final report readme

- src/_data/build_info.json
- src/tests/resampler-smoke/app.js
- src/tests/resampler-smoke/index.njk
- Adding foundation for A/B testing
- Simple logging for sample rate, base latency, and computed buffer size
> Resampler Smoke Test (Part 1)
